### ISSUE TITLE
Collected CSI DATA 

### ISSUE THREAD

**Issue by suwechan** [thu4n/thu4n#1]
We are conducting the same project/thesis using ESP32. 

as we followed and everything was on command. We encountered a problem and it seems that we cannot automatically save the CSI DATAs into comma delimited csv. 

is there any solution to this? We are using ESP32s nodemcu.

**Comment by thu4n** [comment]
Can you provide some more details? Is there any error shown in the log?

**Comment by suwechan** [comment]
The problem is that, we already collected data and in our trials we applied
the noise reduction. However, there were times that we need to modify the
code because there are errors like the CSV file is in UTF 16 encoding or in
different encodings. And the other problem is that the raw collected data
is only in a single column which we think that it must be seperated by
column in the excel, so we need to edit the file and apply delimiters for
it to be separated and after that we apply the denoising.

**Comment by thu4n** [comment]
I have never encountered UTF encoding problem personally so I can't give comments on that. The single column problem though, do you mean the 'CSI_DATA' column? Or the entire thing including MAC, role, etc.. is in one column?

**Comment by suwechan** [comment]
Yes, the CSI_DATA column, the entire thing is in one column. Including the
(csi data, rssi, signal, real time, mac, etc.)

**Comment by suwechan** [comment]
This is the main reason why we cannot proceed to machine learning due to
all the data's are in one column.

**Comment by thu4n** [comment]
> Yes, the CSI_DATA column, the entire thing is in one column. Including the (csi data, rssi, signal, real time, mac, etc.)

Ok that is really strange. If you use the ESP32 CSI Toolkit without modification and only read to csv from serial but this error keep persisting then I suggest you open an Issue in https://github.com/StevenMHernandez/ESP32-CSI-Tool since the problem *might* be because of the toolkit.

If there is any modification or you read the data differently, please provide the details of that here instead, I will try to give it a look.

**Comment by suwechan** [comment]
Thanks for the suggestion, we just opened an issue in the given link.

We will provide our collected data. To be follow.

**Comment by suwechan** [comment]
The command Idf.py monitor | fndstr CSI_DATA (file name), doesn't work.
Don't work means the collected data does not transfer to the said CSV file.

**Comment by suwechan** [comment]
here's our sample of collected CSI_DATA
